const $ = id => document.getElementById(id);
const money = value => value == null ? "Not available" : new Intl.NumberFormat("en-US", { style:"currency", currency:"USD", maximumFractionDigits:0 }).format(value);
const clamp = value => Math.max(0, Math.min(100, Math.round(value)));
const get = (obj, path) => path.split(".").reduce((v, key) => v?.[key], obj) ?? obj?.[path] ?? null;
const STORE = "careershield-v4-comparisons";
const PATHS = {
  college:{label:"College", duration:48, cost:"80000", debt:"40000", earn:"0", career:"Intended career", provider:"School", costLabel:"Estimated total college cost", costHint:"Tuition, fees, and required materials before grants.", aid:"Scholarships and grants", aidHint:"Funding you do not expect to repay."},
  trade:{label:"Skilled trade", duration:36, cost:"5000", debt:"0", earn:"36000", career:"Trade or occupation", provider:"Apprenticeship or employer", hint:"Optional — name the union, employer, or apprenticeship.", costLabel:"Tools, fees, and training cost", costHint:"Your total out-of-pocket cost across the apprenticeship.", aid:"Employer or program support", aidHint:"Funding, reimbursements, or stipends you do not repay."},
  training:{label:"Certification / training", duration:9, cost:"12000", debt:"5000", earn:"0", career:"Target career", provider:"Certification or training provider", hint:"Optional — name the credential, bootcamp, or school.", costLabel:"Total program cost", costHint:"Tuition, exam fees, equipment, and required materials.", aid:"Grants or employer support", aidHint:"Funding or reimbursement you do not repay."},
  military:{label:"Military", duration:4, cost:"0", debt:"0", earn:"30000", career:"Military or civilian career target", provider:"Branch and role", hint:"Example: Air Force · Cyber Systems Operations", costLabel:"Upfront personal cost", costHint:"Required costs you expect to pay yourself.", aid:"Bonus or education benefit", aidHint:"Cash bonus or education benefit you reasonably expect to use."}
};
let activePath="college", selectedSchool=null, selectedCareer=null, selectedMilitary=null, comparisons=readStored();

function readStored(){try{const value=JSON.parse(localStorage.getItem(STORE));return Array.isArray(value)?value.slice(0,4):[]}catch{return[]}}
function save(){localStorage.setItem(STORE,JSON.stringify(comparisons))}
function escapeHtml(value=""){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function debounce(fn,delay=350){let timer;return(...args)=>{clearTimeout(timer);timer=setTimeout(()=>fn(...args),delay)}}
async function api(url){const response=await fetch(url);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"The data service could not complete this request.");return data}
function showResults(container,rows,renderer,onPick){container.innerHTML=rows.length?rows.map((row,i)=>`<button type="button" class="result" data-i="${i}">${renderer(row)}</button>`).join(""):`<div class="result"><strong>No matches found</strong><span>Try a broader search.</span></div>`;container.hidden=false;container.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{onPick(rows[Number(button.dataset.i)]);container.hidden=true}))}

const searchSchools=debounce(async()=>{const query=$("schoolSearch").value.trim();if(query.length<2)return;try{const{results}=await api(`/api/schools?search=${encodeURIComponent(query)}`);showResults($("schoolResults"),results,school=>`<strong>${escapeHtml(get(school,"school.name"))}</strong><span>${escapeHtml([get(school,"school.city"),get(school,"school.state")].filter(Boolean).join(", "))}</span>`,school=>{selectedSchool=school;$("schoolSearch").value=get(school,"school.name")||"";$("schoolSelected").innerHTML=`Using College Scorecard data for ${escapeHtml(get(school,"school.name"))}`;$("schoolSelected").hidden=false;const net=get(school,"latest.cost.avg_net_price.overall"),debt=get(school,"latest.aid.median_debt.completers.overall");if(net)$("cost").value=Math.round(net*4);if(debt)$("debt").value=Math.round(debt)})}catch(e){$("schoolResults").innerHTML=`<div class="result"><strong>Search unavailable</strong><span>${escapeHtml(e.message)}</span></div>`;$("schoolResults").hidden=false}});
const searchCareers=debounce(async()=>{const query=$("careerSearch").value.trim();if(query.length<2)return;try{const{results}=await api(`/api/careers?search=${encodeURIComponent(query)}`);showResults($("careerResults"),results,career=>`<strong>${escapeHtml(career.name)}</strong><span>O*NET-SOC ${escapeHtml(career.code)}${career.brightOutlook?" · Bright Outlook":""}</span>`,async career=>{$("careerSearch").value=career.name;$("careerSelected").textContent="Loading career details…";$("careerSelected").hidden=false;try{selectedCareer=await api(`/api/careers?code=${encodeURIComponent(career.code)}`);$("careerSelected").textContent=`O*NET-SOC ${selectedCareer.code} · ${selectedCareer.outlook?.category||"Outlook unavailable"}`;const median=Number(selectedCareer.wage?.annual_median||selectedCareer.wage?.annual_median_over||0);if(median&&!$("startingPay").value)$("startingPay").placeholder=`About ${money(median*.82)}`}catch(e){selectedCareer=null;$("careerSelected").textContent=e.message}})}catch(e){$("careerResults").innerHTML=`<div class="result"><strong>Search unavailable</strong><span>${escapeHtml(e.message)}</span></div>`;$("careerResults").hidden=false}});

async function chooseMappedCareer(career){$("careerSearch").value=career.name;$("careerSelected").textContent="Loading civilian career details…";$("careerSelected").hidden=false;try{selectedCareer=await api(`/api/careers?code=${encodeURIComponent(career.code)}`);$("careerSelected").textContent=`Selected civilian match · ${selectedCareer.name} · ${selectedCareer.code}`;const median=Number(selectedCareer.wage?.annual_median||selectedCareer.wage?.annual_median_over||0);if(median&&!$("startingPay").value)$("startingPay").placeholder=`About ${money(median*.82)}`}catch(e){selectedCareer=null;$("careerSelected").textContent=e.message}}
function renderMilitaryChoice(job){selectedMilitary=job;$("provider").value=job.title;$("militaryJobSearch").value=`${job.code} · ${job.title.replace(/\s*\([^)]*\)\s*$/,"")}`;const choices=job.occupations||[];$("militaryJobSelected").innerHTML=`<strong>${escapeHtml(job.title)}</strong><div class="mapped-careers">${choices.map((career,i)=>`<button type="button" data-career="${i}"><b>${escapeHtml(career.name)}</b><span>${escapeHtml(career.code)}</span></button>`).join("")||"<span>No civilian career matches were returned.</span>"}</div><small>Choose the civilian career this specialty should be evaluated against.</small>`;$("militaryJobSelected").hidden=false;$("militaryJobSelected").querySelectorAll("[data-career]").forEach(button=>button.addEventListener("click",()=>chooseMappedCareer(choices[Number(button.dataset.career)])))}
const searchMilitaryJobs=debounce(async()=>{const query=$("militaryJobSearch").value.trim();if(query.length<2)return;try{const params=new URLSearchParams({military:query,branch:$("militaryBranch").value,track:$("militaryTrack").value});const{results}=await api(`/api/careers?${params}`);showResults($("militaryJobResults"),results,job=>`<strong>${escapeHtml(job.code)} · ${escapeHtml(job.title.replace(/\s*\([^)]*\)\s*$/,"") )}</strong><span>${job.occupations.length} civilian career match${job.occupations.length===1?"":"es"}</span>`,renderMilitaryChoice)}catch(e){$("militaryJobResults").innerHTML=`<div class="result"><strong>Military job search unavailable</strong><span>${escapeHtml(e.message)}</span></div>`;$("militaryJobResults").hidden=false}});

function setPath(path,initial=false){activePath=path;const p=PATHS[path],military=path==="military";document.querySelectorAll(".path-choice").forEach(button=>{const on=button.dataset.path===path;button.classList.toggle("active",on);button.setAttribute("aria-checked",on)});$("schoolField").hidden=path!=="college";$("providerField").hidden=path==="college"||military;$("militaryBranchField").hidden=!military;$("militaryTrackField").hidden=!military;$("militaryJobField").hidden=!military;$("careerLabel").textContent=military?"Civilian career equivalent":p.career;$("careerSearch").placeholder=military?"Choose a mapped career above, or search another":"Try registered nurse";$("providerLabel").textContent=p.provider;$("providerHint").textContent=p.hint||"";$("costLabel").textContent=p.costLabel;$("costHint").textContent=p.costHint;$("aidLabel").textContent=p.aid;$("aidHint").textContent=p.aidHint;$("durationHint").textContent=path==="trade"?"Paid apprenticeships can earn from the first month.":military?"Use months until regular military pay begins.":"Time before entering the target career full time.";if(!initial){$("duration").value=p.duration;$("cost").value=p.cost;$("grants").value="0";$("debt").value=p.debt;$("earnWhile").value=p.earn;$("provider").value="";$("careerSearch").value="";$("careerSelected").hidden=true;selectedCareer=null;selectedMilitary=null;$("militaryJobSearch").value="";$("militaryJobSelected").hidden=true;$("formMessage").textContent=""}}

function aiResilience(career,path){const text=[career.description,...(career.tasks||[])].join(" ").toLowerCase();let score=55;if(/repair|install|operate|inspect|patient|physical|equipment|construction|emergency|maintain|diagnos|treat|hands-on/.test(text))score+=20;if(/negotiate|counsel|supervis|coordinate|care for|public safety/.test(text))score+=10;if(/enter data|compile|routine|prepare reports|process information|clerical/.test(text))score-=15;if(path==="trade")score+=8;if(path==="military")score+=5;return clamp(score)}
function employmentScore(career){const outlook=(career.outlook?.category||"").toLowerCase();if(career.brightOutlook?.length||outlook.includes("bright"))return 90;if(outlook.includes("average")&&!outlook.includes("below"))return 68;if(outlook.includes("below"))return 42;return 55}
function calculate(){const p=PATHS[activePath],median=Number(selectedCareer.wage?.annual_median||selectedCareer.wage?.annual_median_over||0)||null;const starting=Number($("startingPay").value)||Math.round((median||55000)*.82);const gross=Number($("cost").value||0),aid=Number($("grants").value||0),debt=Number($("debt").value||0),duration=Number($("duration").value||0),earnWhile=Number($("earnWhile").value||0),netCost=Math.max(0,gross-aid),upfront=Math.max(0,netCost-debt);const trainingYears=duration/12;const fiveYearEarnings=earnWhile*trainingYears+starting*Math.max(0,5-trainingYears);const fiveYearNet=fiveYearEarnings-netCost-debt*.15;const financial=clamp(42+(fiveYearNet-140000)/7000);const time=clamp(100-duration*1.15);const cost=clamp(100-(upfront/1200)-(debt/900));const demand=employmentScore(selectedCareer);const ai=aiResilience(selectedCareer,activePath);const related=selectedCareer.relatedOccupations?.length||0,industries=selectedCareer.industries?.length||0;const flexibility=clamp(42+related*5+industries*3+(activePath==="military"?5:0));const metrics={"Financial outcome":financial,"Time to earnings":time,"Debt & upfront cost":cost,"Employment demand":demand,"AI resilience":ai,"Career flexibility":flexibility};const score=clamp(financial*.28+time*.17+cost*.18+demand*.15+ai*.12+flexibility*.10);const name=activePath==="college"?get(selectedSchool,"school.name"):($("provider").value.trim()||p.label);return{id:crypto.randomUUID(),path:activePath,pathLabel:p.label,name,career:selectedCareer,inputs:{gross,aid,debt,netCost,upfront,duration,earnWhile,starting},annualMedian:median,fiveYearNet,metrics,score}}
function category(score){return score>=80?["Strong fit","good"]:score>=65?["Promising","good"]:score>=50?["Mixed tradeoffs","mid"]:["Higher risk","low"]}
function card(option,rank){const[label,tone]=category(option.score);const metrics=Object.entries(option.metrics).map(([name,value])=>`<div class="metric"><div class="metric-label"><span>${escapeHtml(name)}</span><strong>${value}</strong></div><div class="bar"><i style="width:${value}%"></i></div></div>`).join("");return`<article class="option-card ${rank===1?"best":""}"><div class="rank">${rank===1?"#1 · LEADING PATH":`#${rank} PATH`}</div><div class="option-body"><div class="path-tag ${option.path}">${escapeHtml(option.pathLabel)}</div><h3>${escapeHtml(option.name)}</h3><div class="career">${escapeHtml(option.career.name)} · ${escapeHtml(option.career.code)}</div><div class="score-row"><div class="big-score">${option.score}<small>/100</small></div><span class="pill ${tone}">${label}</span></div><div class="facts"><div class="fact"><span>5-year net earnings</span><strong>${money(option.fiveYearNet)}</strong></div><div class="fact"><span>Time to earnings</span><strong>${option.inputs.duration} months</strong></div><div class="fact"><span>Cash upfront</span><strong>${money(option.inputs.upfront??option.inputs.netCost)}</strong></div><div class="fact"><span>Expected debt</span><strong>${money(option.inputs.debt)}</strong></div><div class="fact"><span>Expected first-year pay</span><strong>${money(option.inputs.starting)}</strong></div><div class="fact"><span>Career median wage</span><strong>${money(option.annualMedian)}</strong></div></div><div class="metrics">${metrics}</div><div class="source-note">Your inputs + O*NET labor-market signals${option.path==="college"?" + College Scorecard":""}</div><button class="remove" data-remove="${option.id}">Remove path</button></div></article>`}
function render(){const ranked=[...comparisons].sort((a,b)=>b.score-a.score);$("emptyState").hidden=ranked.length>0;$("clearAll").hidden=ranked.length===0;$("comparisonGrid").innerHTML=ranked.map((o,i)=>card(o,i+1)).join("");$("featured").hidden=!ranked.length;if(ranked.length){const best=ranked[0];$("featured").innerHTML=`<div><div class="eyebrow">CURRENT LEADING PATH</div><div class="path-tag light">${escapeHtml(best.pathLabel)}</div><h2>${escapeHtml(best.name)}</h2><p>${escapeHtml(best.career.name)}</p></div><div class="feature-score"><span>CAREERSHIELD SCORE</span><strong>${best.score}</strong><small>/100</small><p>${category(best.score)[0]} across all six factors</p></div>`}document.querySelectorAll("[data-remove]").forEach(b=>b.addEventListener("click",()=>{comparisons=comparisons.filter(o=>o.id!==b.dataset.remove);save();render()}))}

document.querySelectorAll(".path-choice").forEach(b=>b.addEventListener("click",()=>setPath(b.dataset.path)));
$("schoolSearch").addEventListener("input",()=>{selectedSchool=null;$("schoolSelected").hidden=true;searchSchools()});$("careerSearch").addEventListener("input",()=>{selectedCareer=null;$("careerSelected").hidden=true;$("startingPay").value="";searchCareers()});$("militaryJobSearch").addEventListener("input",()=>{selectedMilitary=null;selectedCareer=null;$("militaryJobSelected").hidden=true;$("careerSelected").hidden=true;searchMilitaryJobs()});[$("militaryBranch"),$("militaryTrack")].forEach(select=>select.addEventListener("change",()=>{$("militaryJobSearch").value="";$("militaryJobSelected").hidden=true;selectedMilitary=null;selectedCareer=null}));document.addEventListener("click",e=>{if(!e.target.closest(".searchbox")){$("schoolResults").hidden=true;$("careerResults").hidden=true;$("militaryJobResults").hidden=true}});
$("addOption").addEventListener("click",()=>{$("formMessage").textContent="";if(activePath==="college"&&!selectedSchool)return $("formMessage").textContent="Select a school from the live College Scorecard results.";if(activePath==="military"&&!selectedMilitary)return $("formMessage").textContent="Select a military specialty from the official search results.";if(!selectedCareer)return $("formMessage").textContent=activePath==="military"?"Choose a civilian career match for the military specialty.":"Select a career from the live O*NET results.";if(comparisons.length>=4)return $("formMessage").textContent="Your comparison already has four paths. Remove one to add another.";comparisons.push(calculate());save();render();$("featured").scrollIntoView({behavior:"smooth",block:"start"})});$("clearAll").addEventListener("click",()=>{comparisons=[];save();render()});
$("interestForm").addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,button=$("interestSubmit"),status=$("interestStatus");status.className="form-status";status.textContent="Sending…";button.disabled=true;try{const response=await fetch("/",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams(new FormData(form)).toString()});if(!response.ok)throw new Error();form.reset();status.className="form-status success";status.textContent="Thank you. Your interest was received."}catch{status.className="form-status error";status.textContent="We couldn’t send this right now. Please try again in a moment."}finally{button.disabled=false}});
setPath("college",true);render();
